[package]
name = "omt-send-test-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "omt-send-test-rs"
path = "src/main.rs"

[[bin]]
name = "debug"
path = "src/debug.rs"

[build-dependencies]
bindgen = "0.72.0"

[dependencies]
anyhow = "1"
